name: List Inactive Remote Branches
 
on:
  workflow_dispatch:
    inputs:
      inactive-days:
        description: 'Number of days to consider a branch inactive'
        required: true
        default: 30
  
jobs:
  list-inactive-branches:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Fetch All Branches
      run: git fetch origin '+refs/heads/*:refs/remotes/origin/*'
 
    - name: List Inactive Remote Branches
      run: |
        cd $GITHUB_WORKSPACE
        inactive_days=${{ github.event.inputs.inactive-days }}
        current_time=$(date +%s)
        
        for branch in $(git for-each-ref --format='%(refname:short) %(committerdate:raw)' refs/remotes/origin); do
          branch_name=$(echo $branch | awk '{print $1}')
          last_commit_date=$(echo $branch | awk '{print $2}')
          days_inactive=$(( (current_time - last_commit_date) / 86400 ))
          
          if [ $days_inactive -gt $inactive_days ]; then
            echo "Inactive branch: $branch_name (Last commit: $days_inactive days ago)"
          fi
        done
